# SERVER
server.port=${PORT:8080}

# POSTGRESQL + PGVECTOR DATABASE (Nuvem - Supabase)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USER:postgres.aqctxmcognsmzfveovcx}
spring.datasource.password=${DB_PASSWORD:LicitacaoAdmin26!}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GEMINI API
gemini.api.key=${GEMINI_KEY:AIzaSyAFHy0bj3Lmqao1Q2N54ekXoXaioeKErHk}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.embedding-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent

# TCE CONFIGURATIONS
tce.pdf.url=https://doe-consulta.tce.ce.gov.br/doeconsulta/paginas/consulta-textual-ou-data-edicao-do.xhtml
tce.pdf.storage=./data/tce/
tce.scheduler.cron=0 0 8 * * *

# MULTIPART
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# LOG
logging.level.com.licitacao=DEBUG
